# do not check for utf stamp
Encoding:
  Enabled: false

LineLength:
  Enabled: true
  Max: 128

Documentation:
  Enabled: false

CaseIndentation:
  Enabled: false

MethodLength:
  Enabled: false

CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10
